parameters:
#    onafctes_web.example.class: Onafctes\WebBundle\Example

services:
#    onafctes_web.example:
#        class: %onafctes_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
